[package]
name = "mochi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mochi"
required-features = ["bin"]

[dependencies]
anyhow = { version = "1.0.58", optional = true }
byteorder = "1.4.3"
clap = { version = "3.2.8", features = ["std", "derive"], default-features = false, optional = true }
cpu-time = "1.0.0"
rand = "0.8.5"
rlua = { version = "0.19.2", features = ["builtin-lua54"] }
rustc-hash = "1.1.0"
rustyline = { version = "9.1.2", optional = true }
thiserror = "1.0.31"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["bin"]
bin = ["anyhow", "clap", "rustyline"]
jemalloc = ["jemallocator"]
